### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by IzzySoft** [unlimish/x2vx-android#3]
I'm just wondering what the Internet permission is required for. Does the app reach out to some server to convert the URLs?

And while I am here:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided by a little change to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

PS: Would be nice if you could include an icon with your Fastlane structures (else your app will show up without one at F-Droid), and if possible also some screenshots :wink:

Thanks in advance!

PS: Your app will [become available here](https://apt.izzysoft.de/packages/sh.unlimi.x2vx) at the IzzyOnDroid repo with the next sync around 6 pm UTC. I've created an icon for it by cutting it out of your featureGraphic, so this is what it will look like then:

![image](https://github.com/unlimish/x2vx-android/assets/6781438/6868011f-b891-4d7a-ad02-44ed433b7010)

**Comment by IzzySoft** [comment]
Thanks @unlimish! Will you also take care for that `DEPENDENCY_INFO_BLOCK`?

**Comment by unlimish** [comment]
@IzzySoft I added icon.png for fastlane and disabling dependencies info to Gradle!

**Comment by IzzySoft** [comment]
Thanks! I should have looked outside that PR, too :see_no_evil:
